# This config file is for the CNN-based chess agent model
model_class: "CNN" # Should match one of the model classes in core/torch_models.py

output:
    output_path: &output_path "results/CNN/" # Directory of training results

model:
    n_blocks: 12
    channels: 128
    dropout: 0.2

training: # Specifies the imitation learning, supervised training parameters
    batch_size: 1024
    lr_start: 2.0e-3
    lr_end: 5.0e-6
    weight_decay: 1.0e-2
    train_num_steps: 300000
    grad_clip: 1.0
    eval_every: 5000
    save_every: 5000
    use_amp: True
    use_latest_checkpoint: True
    restart_scheduler: False
