# This config file is for the Transformer-based chess agent model
model_class: "Transformer" # Should match one of the model classes in core/torch_models.py

output:
    output_path: &output_path "results/Transformer/" # Directory of training results

model:
    hidden_size: 256
    n_heads: 8
    num_layers: 3
    ff_dim: 1024
    dropout: 0.2

training: # Specifies the imitation learning, supervised training parameters
    batch_size: 1024
    lr_start: 5.0e-4
    lr_end: 1.0e-5
    weight_decay: 1.0e-2
    train_num_steps: 600000
    grad_clip: 1.0
    eval_every: 5000
    save_every: 5000
    use_amp: True
    use_latest_checkpoint: True
    restart_scheduler: True
